name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Usando la versión más reciente
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Usando la versión más reciente
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v3  # Usando la versión más reciente
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=FrankGalloSanchez_Traductor_Pipeline

  docker:
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Usando la versión más reciente

      - name: List target directory
        run: ls -la target

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t frankgallosanchez23/traducto_actions:latest .
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Run Docker image
        run: |
          docker run --rm -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
          -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
          -e API_KEY=${{ secrets.API_KEY }} \
          -p 8080:8080 frankgallosanchez23/traducto_actions:latest
