name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permission for mvnw
        run: chmod +x ./mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: |
          ./mvnw clean package -e || { echo 'Maven build failed'; exit 1; }

      - name: List Surefire reports
        run: ls -al target/surefire-reports/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build . -t frankgallosanchez23/traductor_actions:${IMAGE_TAG} --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --build-arg DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}

      - name: Push Docker image
        run: docker push frankgallosanchez23/traductor_actions:${IMAGE_TAG}
