name: Docker Build and Push

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x mvnw  # Change permissions for mvnw script

      - name: Build JAR
        run: ./mvnw clean package  # Build the JAR file

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Ensure this secret is configured
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}  # Use the commit SHA as the image tag
          docker build . -t frankgallosanchez23/traductor_actions:${IMAGE_TAG} \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
            --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}  # Pass environment variables as build arguments

      - name: Push Docker image
        run: docker push frankgallosanchez23/traductor_actions:${IMAGE_TAG}  # Push the image with the commit SHA tag
